version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 700
    type:
      - file
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 700
    type:
      - directory
hooks:
   BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 180
      runas: ubuntu
   AfterInstall:
    - location: ./codedeploy/afterInstall.sh
      timeout: 180
      runas: ubuntu
   ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 180
      runas: ubuntu
